In [1]:
import pandas as pd
from pycaret.regression import *
import os

In [2]:
# Establishing path for the folder which contains all the csv files.
input_folder = "/Users/priyakundu/Documents/Data Engineering/Class 6/Final Presentation/Currency Pairs"

# Get a list of all csv files in the input folder
csv_files = [csv_file for csv_file in os.listdir(input_folder) if csv_file.endswith('.csv')]

df_list = []

for csv_file in csv_files:
    # Read the csv file and only extract three required columns
    df_list.append(pd.read_csv(os.path.join(input_folder, csv_file)))

In [3]:
df = pd.concat(df_list, ignore_index=True)

In [4]:
regression_setup = setup(data = df, target='VWAP', train_size=0.7)

In [5]:
best = compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [6]:
scores = []

for i, df_ in enumerate(df_list):
    print(csv_files[i])
    predict_model(best, data = df_)
    scores.append((csv_files[i][:-4], pull()["RMSE"][0]))
    print()

USDHUF.csv

USDCHF.csv

EURGBP.csv

EURJPY.csv

USDMXN.csv

In [7]:
pair_errors = sorted(scores, key = lambda a: a[1])

In [8]:
classes = [*["Forecastable"]*2, *["Partially Forecastable"]*1, *["Non Forecastable"]*2]

In [10]:
data = {"Currency Pairs": [], "Errors": [], "Class": []} 

for i in range(5):
    data["Currency Pairs"].append(pair_errors[i][0])
    data["Errors"].append(pair_errors[i][1])
    data["Class"].append(classes[i])

pd.DataFrame(data).to_csv("/Users/priyakundu/Documents/Data Engineering/Class 6/Final Presentation/Currency Pair Classes.csv")